name: club_blackout
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1+2


environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dynamic_color: ^1.8.1
  shared_preferences: ^2.5.4
  audioplayers: ^6.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - Backgrounds/
    - Icons/
    - assets/data/

  fonts:
    - family: Hyperwave
      fonts:
        - asset: Hyperwave.otf
